twitter:
  consumer_key: bU4qomX1FzuxEmQmpgXd3ylpZ
  consumer_secret: MGBbS9C1HHVhbIMuJVXZY3QQF6QKnUfEHe4lPzpMfmNp5LNp65
  access_token: 1672449872-2Wt30x2Fcpr90kAoWtqHJY1ULp1WWjtBh0ZBlFp
  access_token_secret: 3tdrKcQCoErNED0wbyJHSb6gXs7XNOluGEP6jXeIcFj84
